export const SET_USER = 'SET_USER';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const AUTHCHECK_COMPLETE = 'AUTHCHECK_COMPLETE';
export const SIGN_OUT = 'SIGN_OUT';
export const ENTRY_CREATE_LOADING = 'ENTRY_CREATE_LOADING';
export const ENTRY_CREATE_SUCCESS = 'ENTRY_CREATE_SUCCESS';
